package com.cookyuu.resume_chat.domain;

import com.cookyuu.resume_chat.common.enums.ApplicantStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("Applicant 엔티티 테스트")
class ApplicantTest {

    @Nested
    @DisplayName("createNewApplicant - 정적 팩토리 메서드")
    class CreateNewApplicant {

        @Test
        @DisplayName("성공: 유효한 파라미터로 Applicant 생성")
        void success_validParameters_createsApplicant() {
            // Given
            String email = "test@example.com";
            String name = "홍길동";
            String encodedPassword = "encodedPassword123";

            // When
            Applicant applicant = Applicant.createNewApplicant(email, name, encodedPassword);

            // Then
            assertThat(applicant).isNotNull();
            assertThat(applicant.getEmail()).isEqualTo(email);
            assertThat(applicant.getName()).isEqualTo(name);
            assertThat(applicant.getPassword()).isEqualTo(encodedPassword);
        }

        @Test
        @DisplayName("성공: UUID 자동 생성 검증")
        void success_uuidAutoGenerated() {
            // Given
            String email = "test@example.com";
            String name = "홍길동";
            String encodedPassword = "encodedPassword123";

            // When
            Applicant applicant = Applicant.createNewApplicant(email, name, encodedPassword);

            // Then
            assertThat(applicant.getUuid()).isNotNull();
        }

        @Test
        @DisplayName("성공: 기본 상태 ACTIVE 검증")
        void success_defaultStatusIsActive() {
            // Given
            String email = "test@example.com";
            String name = "홍길동";
            String encodedPassword = "encodedPassword123";

            // When
            Applicant applicant = Applicant.createNewApplicant(email, name, encodedPassword);

            // Then
            assertThat(applicant.getStatus()).isEqualTo(ApplicantStatus.ACTIVE);
        }

        @Test
        @DisplayName("성공: loginFailCnt 초기화 검증 (0)")
        void success_loginFailCntInitializedToZero() {
            // Given
            String email = "test@example.com";
            String name = "홍길동";
            String encodedPassword = "encodedPassword123";

            // When
            Applicant applicant = Applicant.createNewApplicant(email, name, encodedPassword);

            // Then
            assertThat(applicant.getLoginFailCnt()).isEqualTo(0);
        }

        @Test
        @DisplayName("성공: 여러 Applicant 생성 시 각각 다른 UUID 생성")
        void success_differentUuidsForMultipleApplicants() {
            // Given
            String email1 = "test1@example.com";
            String email2 = "test2@example.com";
            String name = "홍길동";
            String encodedPassword = "encodedPassword123";

            // When
            Applicant applicant1 = Applicant.createNewApplicant(email1, name, encodedPassword);
            Applicant applicant2 = Applicant.createNewApplicant(email2, name, encodedPassword);

            // Then
            assertThat(applicant1.getUuid()).isNotEqualTo(applicant2.getUuid());
        }
    }

    @Nested
    @DisplayName("Builder 패턴 테스트")
    class BuilderPattern {

        @Test
        @DisplayName("성공: 빌더로 모든 필드 설정")
        void success_builderWithAllFields() {
            // Given & When
            Applicant applicant = Applicant.builder()
                    .email("test@example.com")
                    .name("홍길동")
                    .password("encodedPassword")
                    .status(ApplicantStatus.ACTIVE)
                    .loginFailCnt(0)
                    .build();

            // Then
            assertThat(applicant).isNotNull();
            assertThat(applicant.getEmail()).isEqualTo("test@example.com");
            assertThat(applicant.getName()).isEqualTo("홍길동");
            assertThat(applicant.getPassword()).isEqualTo("encodedPassword");
            assertThat(applicant.getStatus()).isEqualTo(ApplicantStatus.ACTIVE);
            assertThat(applicant.getLoginFailCnt()).isEqualTo(0);
        }
    }
}
